name: Generate Image List

on:
  push:
    paths:
      - "imagesGrubby/**"
      - "imagesMarshal/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Reset project files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull --rebase

      - name: Generate Image List
        run: |
          echo "var imageListGrubby = [" > scripts/imageList.js
          ls imagesGrubby/* | xargs -I {} echo "'{}'," >> scripts/imageList.js
          echo "];" >> scripts/imageList.js
          echo "var imageListMarshal = [" >> scripts/imageList.js
          ls imagesMarshal/* | xargs -I {} echo "'{}'," >> scripts/imageList.js
          echo "];" >> scripts/imageList.js

      - name: Commit and Push
        run: |
          git add scripts/imageList.js
          git commit -m "Update image list" -a
          git push
